FROM cseelye/linux-shell

ARG VCS_REF=unknown
ARG BUILD_DATE=unknown
ARG VERSION=0.0
LABEL maintainer="cseelye@gmail.com" \
      org.opencontainers.image.authors="cseelye@gmail.com" \
      org.opencontainers.image.title="sfauto" \
      org.opencontainers.image.description="Container for running sfauto scripts" \
      org.opencontainers.image.utl="https://github.com/cseelye/sfauto" \
      org.opencontainers.image.revision="${VCS_REF}" \
      org.opencontainers.image.created="${BUILD_DATE}" \
      org.opencontainers.image.version="${VERSION}"

COPY . /sfauto
RUN pip install -U pip --index-url http://repoproxy-rtp.eng.netapp.com:8081/artifactory/api/pypi/python-package-index/simple --trusted-host repoproxy-rtp.eng.netapp.com && \
    pip install -U -r /sfauto/requirements.txt --index-url http://repoproxy-rtp.eng.netapp.com:8081/artifactory/api/pypi/python-package-index/simple --trusted-host repoproxy-rtp.eng.netapp.com && \
    pip install -U -r /sfauto/requirements-test.txt --index-url http://repoproxy-rtp.eng.netapp.com:8081/artifactory/api/pypi/python-package-index/simple --trusted-host repoproxy-rtp.eng.netapp.com && \
    pip install yamllint --index-url http://repoproxy-rtp.eng.netapp.com:8081/artifactory/api/pypi/python-package-index/simple --trusted-host repoproxy-rtp.eng.netapp.com
WORKDIR /sfauto
CMD ["/bin/bash"]
