#!/bin/bash
set -x

: ${MAC_ADDRESS:=}

: ${PXE_SERVER:=192.168.100.4}
[[ -z ${MAC_ADDRESS} ]] && { echo "Missing MAC_ADDRESS"; exit 1; }
sshpass -p SolidF1r3 ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -l root ${PXE_SERVER} "rm /tftpboot/pxelinux.cfg/01-$(echo ${MAC_ADDRESS} | tr ':' '-' | tr '[:upper:]' '[:lower:]')"
set +x

