#!/bin/bash
set -eu

# Create the container image if it does not exist
if ! docker images --format '{{.Repository}}:{{.Tag}}' | grep -q sfauto; then
    echo
    echo "======================================="
    echo "    One-time build SFAUTO docker image"
    echo "======================================="
    echo
    echo
    docker build --force-rm --tag sfauto .
    echo "Finished building sfauto docker image"
    echo
fi

# If the user did not supply a command to run, start the container with an interactive shell
if [[ $# -le 0 ]]; then
    echo
    echo "======================================="
    echo " Entering SFAUTO docker container"
    echo "======================================="
    echo
    cmd="/bin/bash"

# If the user specified a command, run that command in the container
else
    cmd="$*"
fi

# Start the container
eval HOMEDIR="~"
docker run --rm --interactive --tty --volume $(pwd):/sfauto --volume ${HOMEDIR}/.bashrc:/root/.bashrc --workdir /sfauto --hostname sfauto-container --name sfauto-container sfauto ${cmd}
